# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import extension.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', extension.fields.RandomFixedCharField(editable=False, max_length=16, unique=True, verbose_name='编号')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('link', models.URLField(default='', verbose_name='链接')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updation_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源管理',
                'verbose_name_plural': '资源管理',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', extension.fields.RandomFixedCharField(editable=False, max_length=6, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资源类型',
                'verbose_name_plural': '资源类型',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='collection.ResourceType', verbose_name='类型'),
        ),
    ]
